from django.db import models
import datetime

class table1(models.Model):
    id = models.AutoField(primary_key=True,auto_created=True,)
    设备编号 = models.CharField(max_length=20,default = '',)
    资产编号 = models.CharField(max_length=20,default = '',)
    设备名称 = models.CharField(max_length=20,default = '',)
    设备型号 = models.CharField(max_length=20,default = '',)
    设备规格 = models.CharField(max_length=20,default = '',)
    制造厂 = models.CharField(max_length=20,default = '',)
    出厂年月 = models.CharField(max_length=20,default = '',)
    使用部门 = models.CharField(max_length=20,default = '',)
    安装地点 = models.CharField(max_length=20,default = '',)
    立卡年月 = models.CharField(max_length=20,default = '',)
    启用年月 = models.CharField(max_length=20,default = '',)
    ABC分类 = models.CharField(max_length=20,default = '',)
    财务分类 = models.CharField(max_length=20,default = '',)
    原值元 = models.CharField(max_length=20,default = '',)
    完好状态 = models.CharField(max_length=20,default = '',)
    当前管理状态 = models.CharField(max_length=20,default = '',)
    状态变动日期 = models.CharField(max_length=20,default = '',)
    使用年限年 = models.CharField(max_length=20,default = '',)
    供货商 = models.CharField(max_length=20,default = '',)
    出厂编号 = models.CharField(max_length=20,default = '',)
    单价元 = models.CharField(max_length=20,default = '',)
    设备属性 = models.CharField(max_length=20,default = '',)
    生产用途 = models.CharField(max_length=20,default = '',)
    责任人 = models.CharField(max_length=20,default = '',)
    备注 = models.CharField(max_length=20,default = '',)
