# Generated by Django 3.2.18 on 2023-05-18 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='table1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('设备', models.CharField(blank=True, default='', max_length=20, verbose_name='设备')),
                ('名称', models.CharField(blank=True, default='', max_length=20, verbose_name='名称')),
                ('规格型号', models.CharField(blank=True, default='', max_length=20, verbose_name='规格型号')),
                ('承修单', models.CharField(blank=True, default='', max_length=20, verbose_name='承修单')),
                ('维修费', models.CharField(blank=True, default='', max_length=20, verbose_name='维修费')),
                ('维修主要', models.CharField(blank=True, default='', max_length=20, verbose_name='维修主要')),
                ('原因分', models.CharField(blank=True, default='', max_length=20, verbose_name='原因分')),
                ('验收时', models.CharField(blank=True, default='', max_length=20, verbose_name='验收时')),
                ('保质期', models.CharField(blank=True, default='', max_length=20, verbose_name='保质期')),
                ('付款', models.CharField(blank=True, default='', max_length=20, verbose_name='付款')),
            ],
        ),
    ]
