# Generated by Django 3.2.18 on 2023-05-18 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('维修情况', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table1',
            name='名称',
        ),
        migrations.RemoveField(
            model_name='table1',
            name='设备',
        ),
        migrations.AddField(
            model_name='table1',
            name='设备名称',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='设备名称'),
        ),
        migrations.AddField(
            model_name='table1',
            name='设备编号',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='设备编号'),
        ),
    ]
