# Generated by Django 3.2.18 on 2023-06-13 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='table1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('年份', models.CharField(blank=True, default='', max_length=20, verbose_name='年份')),
                ('月份', models.CharField(blank=True, default='', max_length=20, verbose_name='月份')),
                ('电使用量千瓦时', models.CharField(blank=True, default='', max_length=20, verbose_name='电使用量(千瓦时)')),
                ('使用部门', models.CharField(blank=True, default='', max_length=20, verbose_name='使用部门')),
            ],
        ),
        migrations.CreateModel(
            name='tempModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
