# Generated by Django 3.2.18 on 2023-05-18 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='table1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('设备编号', models.CharField(blank=True, default='', max_length=20, verbose_name='设备编号')),
                ('资产编号', models.CharField(blank=True, default='', max_length=20, verbose_name='资产编号')),
                ('设备名称', models.CharField(blank=True, default='', max_length=20, verbose_name='设备名称')),
                ('设备型号', models.CharField(blank=True, default='', max_length=20, verbose_name='设备型号')),
                ('设备规格', models.CharField(blank=True, default='', max_length=20, verbose_name='设备规格')),
                ('制造厂', models.CharField(blank=True, default='', max_length=20, verbose_name='制造厂')),
                ('使用部门', models.CharField(blank=True, default='', max_length=20, verbose_name='使用部门')),
            ],
        ),
    ]
