# Generated by Django 3.2.18 on 2023-05-12 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='table1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('设备编号', models.CharField(blank=True, default='', max_length=20, verbose_name='设备编号')),
                ('设备名称', models.CharField(blank=True, default='', max_length=20, verbose_name='设备名称')),
                ('运行时间', models.DateTimeField(default=0, verbose_name='运行时间')),
                ('开机时间', models.DateTimeField(default=0, verbose_name='开机时间')),
                ('关机时间', models.DateTimeField(default=0, verbose_name='关机时间')),
                ('使用时间', models.FloatField(default=0.0, verbose_name='使用时间')),
                ('耗材使用', models.CharField(blank=True, default='', max_length=20, verbose_name='耗材使用')),
            ],
        ),
    ]
