# Generated by Django 3.2.18 on 2023-05-12 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('使用时长', '0003_auto_20230512_0452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table1',
            name='运行时间',
            field=models.CharField(default=0.0, max_length=20, verbose_name='运行时间'),
        ),
    ]
