# Generated by Django 3.2.18 on 2023-05-12 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('使用时长', '0004_alter_table1_运行时间'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table1',
            name='运行时间',
            field=models.DateTimeField(default=0.0, verbose_name='运行时间'),
        ),
    ]
