# Generated by Django 3.2.18 on 2023-05-12 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('使用时长', '0005_alter_table1_运行时间'),
    ]

    operations = [
        migrations.RenameField(
            model_name='table1',
            old_name='运行时间',
            new_name='开机时间',
        ),
    ]
