# Generated by Django 3.2.18 on 2023-06-08 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('用水量', '0002_table1_使用部门'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table1',
            name='使用部门',
        ),
    ]
