# Generated by Django 3.2.18 on 2023-06-12 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('用水量', '0004_table1_使用部门'),
    ]

    operations = [
        migrations.CreateModel(
            name='tempModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
