# Generated by Django 3.2.14 on 2023-03-31 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='table1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('设备编号', models.CharField(default='', max_length=20)),
                ('资产编号', models.CharField(default='', max_length=20)),
                ('设备名称', models.CharField(default='', max_length=20)),
                ('设备型号', models.CharField(default='', max_length=20)),
                ('设备规格', models.CharField(default='', max_length=20)),
                ('制造厂', models.CharField(default='', max_length=20)),
                ('出厂年月', models.CharField(default='', max_length=20)),
                ('使用部门', models.CharField(default='', max_length=20)),
                ('安装地点', models.CharField(default='', max_length=20)),
                ('立卡年月', models.CharField(default='', max_length=20)),
                ('启用年月', models.CharField(default='', max_length=20)),
                ('ABC分类', models.CharField(default='', max_length=20)),
                ('财务分类', models.CharField(default='', max_length=20)),
                ('原值元', models.CharField(default='', max_length=20)),
                ('完好状态', models.CharField(default='', max_length=20)),
                ('当前管理状态', models.CharField(default='', max_length=20)),
                ('状态变动日期', models.CharField(default='', max_length=20)),
                ('使用年限年', models.CharField(default='', max_length=20)),
                ('供货商', models.CharField(default='', max_length=20)),
                ('出厂编号', models.CharField(default='', max_length=20)),
                ('单价元', models.CharField(default='', max_length=20)),
                ('设备属性', models.CharField(default='', max_length=20)),
                ('生产用途', models.CharField(default='', max_length=20)),
                ('责任人', models.CharField(default='', max_length=20)),
                ('备注', models.CharField(default='', max_length=20)),
            ],
        ),
    ]
