# Generated by Django 3.2.14 on 2023-03-21 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='table1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=20, verbose_name='使用部门')),
            ],
        ),
        migrations.CreateModel(
            name='table2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=20, verbose_name='设备名称')),
            ],
        ),
        migrations.CreateModel(
            name='table3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('设备编号', models.CharField(default='', max_length=20)),
                ('设备型号', models.CharField(default='', max_length=20)),
                ('设备规格', models.CharField(default='', max_length=20)),
                ('制造商', models.CharField(default='', max_length=20)),
            ],
        ),
    ]
