# Generated by Django 3.2.18 on 2023-05-12 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('使用时长', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='table1',
            new_name='wokao',
        ),
    ]
