# Generated by Django 3.2.18 on 2023-05-12 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('使用时长', '0007_auto_20230512_0502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table1',
            name='关机时间',
            field=models.DateTimeField(default=0.0, verbose_name='关机时间'),
        ),
    ]
