# Generated by Django 3.2.18 on 2023-05-18 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('使用时长', '0009_table1_操作时间'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table1',
            name='关机时间',
            field=models.DateTimeField(blank=True, default=0.0, verbose_name='关机时间'),
        ),
        migrations.AlterField(
            model_name='table1',
            name='开机时间',
            field=models.DateTimeField(blank=True, default=0.0, verbose_name='开机时间'),
        ),
        migrations.AlterField(
            model_name='table1',
            name='操作时间',
            field=models.FloatField(blank=True, default=0.0, verbose_name='操作时间'),
        ),
    ]
