# Generated by Django 3.2.18 on 2023-05-18 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('使用时长', '0011_auto_20230517_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='table1',
            name='使用部门',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='使用部门'),
        ),
    ]
