# Generated by Django 3.2.18 on 2023-05-11 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='table1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('设备编号', models.CharField(blank=True, default='', max_length=20, verbose_name='设备编号')),
                ('设备名称', models.CharField(blank=True, default='', max_length=20, verbose_name='设备名称')),
            ],
        ),
    ]
