# Generated by Django 3.2.18 on 2023-05-24 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='table1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('统计时间', models.CharField(blank=True, default='', max_length=20, verbose_name='统计时间')),
                ('水使用量吨', models.CharField(blank=True, default='', max_length=20, verbose_name='水使用量(吨)')),
                ('水花费元', models.CharField(blank=True, default='', max_length=20, verbose_name='水花费(元)')),
                ('电使用量千瓦时', models.CharField(blank=True, default='', max_length=20, verbose_name='电使用量(千瓦时)')),
                ('电花费元', models.CharField(blank=True, default='', max_length=20, verbose_name='电花费(元)')),
                ('二氧化碳使用量吨', models.CharField(blank=True, default='', max_length=20, verbose_name='二氧化碳使用量(吨)')),
                ('二氧化碳花费元', models.CharField(blank=True, default='', max_length=20, verbose_name='二氧化碳花费(元)')),
                ('液氧使用量吨', models.CharField(blank=True, default='', max_length=20, verbose_name='液氧使用量(吨)')),
                ('液氧花费元', models.CharField(blank=True, default='', max_length=20, verbose_name='液氧花费(元)')),
                ('氩气使用量吨', models.CharField(blank=True, default='', max_length=20, verbose_name='氩气使用量(吨)')),
                ('氩气花费元', models.CharField(blank=True, default='', max_length=20, verbose_name='氩气花费(元)')),
                ('丙烷使用量', models.CharField(blank=True, default='', max_length=20, verbose_name='丙烷使用量(kg)')),
                ('丙烷花费元', models.CharField(blank=True, default='', max_length=20, verbose_name='丙烷花费(元)')),
                ('混合气使用量瓶', models.CharField(blank=True, default='', max_length=20, verbose_name='混合气使用量(瓶)')),
                ('混合器花费元', models.CharField(blank=True, default='', max_length=20, verbose_name='混合器花费(元)')),
            ],
        ),
    ]
