# Generated by Django 3.2.18 on 2023-05-24 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('武汉厂区', '0002_alter_table1_统计时间'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table1',
            name='统计时间',
            field=models.DateTimeField(blank=True, verbose_name='统计时间'),
        ),
    ]
