# Generated by Django 3.2.18 on 2023-05-25 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('武汉厂区', '0003_alter_table1_统计时间'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table1',
            name='统计时间',
        ),
        migrations.AddField(
            model_name='table1',
            name='年份',
            field=models.CharField(blank=True, max_length=20, verbose_name='年份'),
        ),
        migrations.AddField(
            model_name='table1',
            name='月份',
            field=models.CharField(blank=True, max_length=20, verbose_name='月份'),
        ),
        migrations.AlterField(
            model_name='table1',
            name='丙烷使用量',
            field=models.FloatField(blank=True, default=0.0, max_length=20, verbose_name='丙烷使用量(kg)'),
        ),
        migrations.AlterField(
            model_name='table1',
            name='丙烷花费元',
            field=models.FloatField(blank=True, default=0.0, max_length=20, verbose_name='丙烷花费(元)'),
        ),
        migrations.AlterField(
            model_name='table1',
            name='二氧化碳使用量吨',
            field=models.FloatField(blank=True, default=0.0, max_length=20, verbose_name='二氧化碳使用量(吨)'),
        ),
        migrations.AlterField(
            model_name='table1',
            name='二氧化碳花费元',
            field=models.FloatField(blank=True, default=0.0, max_length=20, verbose_name='二氧化碳花费(元)'),
        ),
        migrations.AlterField(
            model_name='table1',
            name='氩气使用量吨',
            field=models.FloatField(blank=True, default=0.0, max_length=20, verbose_name='氩气使用量(吨)'),
        ),
        migrations.AlterField(
            model_name='table1',
            name='氩气花费元',
            field=models.FloatField(blank=True, default=0.0, max_length=20, verbose_name='氩气花费(元)'),
        ),
        migrations.AlterField(
            model_name='table1',
            name='水使用量吨',
            field=models.FloatField(blank=True, default=0.0, max_length=20, verbose_name='水使用量(吨)'),
        ),
        migrations.AlterField(
            model_name='table1',
            name='水花费元',
            field=models.FloatField(blank=True, default=0.0, max_length=20, verbose_name='水花费(元)'),
        ),
        migrations.AlterField(
            model_name='table1',
            name='液氧使用量吨',
            field=models.FloatField(blank=True, default=0.0, max_length=20, verbose_name='液氧使用量(吨)'),
        ),
        migrations.AlterField(
            model_name='table1',
            name='液氧花费元',
            field=models.FloatField(blank=True, default=0.0, max_length=20, verbose_name='液氧花费(元)'),
        ),
        migrations.AlterField(
            model_name='table1',
            name='混合器花费元',
            field=models.FloatField(blank=True, default=0.0, max_length=20, verbose_name='混合器花费(元)'),
        ),
        migrations.AlterField(
            model_name='table1',
            name='混合气使用量瓶',
            field=models.FloatField(blank=True, default=0.0, max_length=20, verbose_name='混合气使用量(瓶)'),
        ),
        migrations.AlterField(
            model_name='table1',
            name='电使用量千瓦时',
            field=models.FloatField(blank=True, default=0.0, max_length=20, verbose_name='电使用量(千瓦时)'),
        ),
        migrations.AlterField(
            model_name='table1',
            name='电花费元',
            field=models.FloatField(blank=True, default=0.0, max_length=20, verbose_name='电花费(元)'),
        ),
    ]
